import 'package:easy_localization/easy_localization.dart';
import 'package:signin_proj/generated/locale_keys.g.dart';

String non_text_txt = LocaleKeys.Please_enter_some_text.tr();
String non_email_txt = LocaleKeys.Please_enter_a_valid_email.tr();
String email_txt = LocaleKeys.Email.tr();
String enter_email_txt = LocaleKeys.Enter_your_email.tr();
String short_pswd_txt = LocaleKeys.Password_must_be_at_least_6_characters.tr();
String pswd_txt = LocaleKeys.Password.tr();
String wnter_pswd_txt = LocaleKeys.Enter_your_password.tr();
String remember_txt = LocaleKeys.Remember_me.tr();
String sign_in_txt = LocaleKeys.Sign_in.tr();
String logo_txt = LocaleKeys.Logo.tr();
String body_txt = LocaleKeys.Body.tr();
String setting_txt = LocaleKeys.Settings.tr();
String sign_out_txt = LocaleKeys.Sign_Out.tr();
String acc_txt = LocaleKeys.Account.tr();
String main_txt = LocaleKeys.Main.tr();
String posts_txt = LocaleKeys.Posts.tr();
String folls_txt = LocaleKeys.Followers.tr();
String fillings_txt = LocaleKeys.Following.tr();
String name_sur_txt = LocaleKeys.Nikita_Serebrenitskii.tr();